import React from "react";
import Head from "next/head";
import Header from "@/components/Header";
import styles from "../styles/Home.module.css";
import About from "@/components/About";
export default function Home() {
	return (
		<>
			<Head>
				<title>Portfólio João Vitor Costa</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Header/>
				<About/>
			</main>
		</>
	);
}
